In [6]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [18]:
# read in all the words
words = open('names.txt','r').read().splitlines()

In [25]:
# build vocab of words
chars = sorted(list(set(''.join(words))))
stoi = {s:i +1 for i,s in enumerate(chars)}
stoi ['.'] = 0
itos = {i:s for s,i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [71]:
# building the context window
X,Y = [], []
context_size = 3

for word in words[:5]:
    context = [0] * context_size # re-initalize the context for each word
    for ch in word + '.':
        # convert the ch to interger
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print("".join(itos[i] for i in context), '-->', itos[ix])
        context = context[1:] + [ix]
X = torch.tensor(X)
Y =  torch.tensor(Y)

... --> e
..e --> m
.em --> m
emm --> a
mma --> .
... --> o
..o --> l
.ol --> i
oli --> v
liv --> i
ivi --> a
via --> .
... --> a
..a --> v
.av --> a
ava --> .
... --> i
..i --> s
.is --> a
isa --> b
sab --> e
abe --> l
bel --> l
ell --> a
lla --> .
... --> s
..s --> o
.so --> p
sop --> h
oph --> i
phi --> a
hia --> .


In [72]:
C = torch.randn((27,2))

In [73]:
C[5]

tensor([0.1222, 0.6176])

In [74]:
F.one_hot(torch.tensor(5), num_classes = 27).float() @ C

tensor([0.1222, 0.6176])

In [75]:
X.shape

torch.Size([32, 3])

In [76]:
X[13,2]

tensor(1)

In [80]:
C[X].shape

torch.Size([32, 3, 2])

In [ ]:
W1 = torch.randn()

we have 3 words as input: each word has a 2d embedding. 

Trainig dataset X: (N,3) - each word is represented by an index but each index actually corresponds to a 2D vector. 

C (look up)- is (27, 2) - each character is represented by a 2D row.

The neural network will take 3 words has inputs where each word is represented by a 2D vector.
Therefore the input is actually 3 vectors that that are 2x1 each

In [87]:
C[X][0] # this is the embedding rep of  0,0,0

tensor([[0.6093, 0.2906],
        [0.6093, 0.2906],
        [0.6093, 0.2906]])

In [88]:
X[0].shape

torch.Size([3])

In [92]:
W1 = torch.randn((6,100))
b1 = torch.randn(100)

In [91]:
W1[0]

tensor([ 8.2631e-01,  1.2592e+00, -3.1391e-01, -2.3158e+00,  5.5852e-02,
        -4.3301e-01, -1.0031e+00,  2.4420e+00, -1.3918e+00,  5.9667e-01,
        -1.4062e+00,  7.5446e-01,  4.4328e-02,  5.1265e-01, -7.6608e-01,
         6.7884e-01, -8.8897e-01,  1.4501e+00,  8.5490e-01,  8.0265e-01,
         1.4870e+00, -2.5551e-01, -4.1253e-01, -1.3945e-02,  6.7045e-01,
        -1.3455e-01, -1.9233e-01,  3.6077e+00,  1.4214e+00,  9.3722e-01,
        -1.0542e-01, -3.6059e-02, -7.2792e-02,  3.0792e-01,  3.5280e-01,
         7.7087e-01, -9.1241e-01, -7.4117e-01, -1.5080e+00,  2.6585e-01,
         9.0664e-02,  6.2571e-03, -2.6252e-02,  6.4823e-01, -1.2180e+00,
         1.4476e-02, -9.1479e-01, -1.3511e+00, -5.9680e-01,  9.1080e-01,
        -9.0208e-01, -1.4956e+00,  4.1448e-01, -3.1036e-01,  1.4176e-01,
        -9.7890e-01,  1.0526e+00, -1.7523e+00,  9.6592e-01, -1.5601e+00,
        -7.5268e-01, -4.6281e-01,  2.2448e-01,  7.1603e-01,  1.7116e+00,
        -2.1605e+00, -6.9811e-02, -4.3650e-02,  1.9